---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies and start"
  shell: |
    cd ~/backend-app
    npm i

- name: display ENV PORT
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'TYPEORM_PORT') }}"
- name: display ENV MIGRATION
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
- name: display ENV HOST
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'TYPEORM_HOST') }}"

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app
    pm2 stop default
    pm2 start npm -- start

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
# - name: "Configure pm2 to start as service"
#   shell: |
#     sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#     pm2 save
